import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
// Generated by `wxt prepare` (imports.eslintrc.enabled: 9) — exposes WXT's auto-imported
// globals (defineBackground, defineContentScript, browser, …) so they aren't flagged.
import autoImports from './.wxt/eslint-auto-imports.mjs';

export default tseslint.config(
  { ignores: ['.wxt/**', '.output/**', 'node_modules/**'] },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  autoImports,
  prettier,
  // World boundary (enforced): the MAIN-world reader and the pure modules it pulls in must NOT use
  // the extension-API globals `browser` / `storage` — they are undefined in the MAIN world and would
  // throw at runtime with no type/CI signal. Keep persistence/messaging in the isolated content script.
  {
    files: [
      'entrypoints/feed-reader.content.ts',
      'entrypoints/content/feed/**/*.ts',
      'entrypoints/content/dom.ts',
      'entrypoints/content/gate.ts',
      'entrypoints/content/observer.ts',
      'entrypoints/content/parse/**/*.ts',
    ],
    rules: {
      'no-restricted-globals': [
        'error',
        {
          name: 'browser',
          message:
            'Extension APIs are unavailable in the MAIN world — keep browser/storage in the isolated content script.',
        },
        {
          name: 'storage',
          message:
            'Extension APIs are unavailable in the MAIN world — keep browser/storage in the isolated content script.',
        },
      ],
    },
  },
);
