import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';
// Generated by `wxt prepare` (imports.eslintrc.enabled: 9) — exposes WXT's auto-imported
// globals (defineBackground, defineContentScript, browser, …) so they aren't flagged.
import autoImports from './.wxt/eslint-auto-imports.mjs';

export default tseslint.config(
  { ignores: ['.wxt/**', '.output/**', 'node_modules/**'] },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  autoImports,
  prettier,
);
